---
name: Benchmark
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Do not deploy image to Gist
        default: true
jobs:
  benchmark:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install . matplotlib pycryptodome rc4
    - run: nice -19 python benchmark.py -o benchmark.svg
    - uses: actions/upload-artifact@v3
      with:
        name: benchmark
        path: benchmark.svg
    - uses: exuanbo/actions-deploy-gist@v1
      if: github.event.inputs.dry-run != 'true'
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: '991d0c197e1cb62eec81edec65363187'
        file_path: benchmark.svg
