---
name: Lint
on:
- push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      run: clang-format --Werror --dry-run arc4.c
    - run: pip install flake8 pygments restructuredtext_lint
    - run: flake8
    - run: rst-lint README.rst
