---
name: test
on:
- push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 2.7
        - 3.5
        - 3.6
        - 3.7
        - 3.8
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python-version }}"
    - run: python setup.py install
    - run: python -munittest discover --verbose
